site:
  title: SUSE® Virtualization 
  url: /
  start_page: v1.5@virtualization:en:introduction/overview.adoc
content:
  sources:
  - url: ./
    branches: HEAD
    start_paths: [versions/v1.3, versions/v1.4, versions/v1.5, versions/v1.6]
ui:
  bundle:
    url: https://github.com/SUSEdoc/dsc-style-bundle/blob/main/default-ui/ui-bundle.zip?raw=true
    snapshot: true
  supplemental_files: ./dsc-style-bundle/supplemental-files/rancher
asciidoc:
  extensions:
    - '@asciidoctor/tabs'
antora:
  extensions:
  - require: '@antora/lunr-extension'
  - require: ./product-docs-common/extensions/dynamic-loading-attributes/load-global-site-attributes.js
    attributefile: ./product-docs-common/global-attributes.yml
    enabled: true
